### ISSUE TITLE
Thresholds and resulting points

### ISSUE THREAD

**Issue by Starcounter-Jack** [NaokiHori/MarchingSquares#2]
As cells approaches thresholds, the generated points approach each other as duplicates.

```
    const size_t sizes[2] = {5, 5};
    const double threshold = 0.9999;
    double values[] = {0.0, 0.0, 0.0, 0.0, 0.0,
                       0.0, 1.0, 1.0, 1.0, 0.0,
                       0.0, 1.0, 1.0, 1.0, 0.0,
                       0.0, 1.0, 1.0, 1.0, 0.0,
                       0.0, 0.0, 0.0, 0.0, 0.0};
```

```
Generated cluster:

point (1.000000, 0.999900)
point (2.000000, 0.999900)
point (3.000000, 0.999900)
point (3.000100, 1.000000)
point (3.000100, 2.000000)
point (3.000100, 3.000000) // The distances between some points will have  infinitesimal ...
point (3.000000, 3.000100) // ...distances at the point that they meet the threshold condition
point (2.000000, 3.000100)
point (1.000000, 3.000100)
point (0.999900, 3.000000)
point (0.999900, 2.000000)
```

**Comment by Starcounter-Jack** [comment]
Maybe there should be a threshold for minimum point distances to avoid long runs of duplicates.

This would also allow a cell value equaling the threshold to meet the threshold criteria rather than having to exceed it.

```
// flag each vertex
            vertices_t vertices = 0;
            for (size_t n = 0; n < 4; n++)
            {
                const bool is_above = (lvals[n] > threshold);        // Why not  (lvals[n] >= threshold?
                vertices |= (1 & (unsigned int)(is_above)) << n;
            }
```

**Comment by Starcounter-Jack** [comment]
An alternative to eliminating points approaching duplication is to use this simple algorithm to avoid datapoints that does not add to the contour. The square marching is an approximation due to its grid and interpolation, so it would not make sense to provide an excessive amount of points that does not bend the curves. 

https://en.wikipedia.org/wiki/Visvalingam–Whyatt_algorithm

**Comment by NaokiHori** [comment]
Thanks for your comment.

Indeed I notice this issue, and I agree that Visvalingam–Whyatt algorithm could be a promising way to avoid this kind of artifacts.
I might implement it in the near future as an additional functionality.

However, for the time being, I would like to keep the original naive implementation in order to reduce the complexity.
Since VW algorithm can take a polygonal chain as input, I think users can easily implement and use it as a post-processing when necessary.

**Comment by NaokiHori** [comment]
Now Visvalingam–Whyatt algorithm has been implemented in the code as a post-processing.

Thanks a lot for your suggestion.
