### ISSUE TITLE
Very nice implementation

### ISSUE THREAD

**Issue by Starcounter-Jack** [NaokiHori/MarchingSquares#4]
Thanks for sharing this work. This is a very clean implementation. I'm planning to use a derivative of this work for some browser animations.  
 
 I'll report any bugs or other findings as I'm deploying it.

**Comment by NaokiHori** [comment]
Thanks for your kind comment.
Glad to hear that, looking forward to your work :)
Also I appreciate all bug reports and suggestions for polishing the project.
